---
#==========================================================#
# prettier ships with a handful of format options
# that can be changed in this yaml configuration file
#
# prettier.io/docs/en/options.html
# prettier.io/docs/en/configuration.html
# yaml.org
#==========================================================#

#==========================================================#
# options set in .editorconfig

#useTabs: false
#tabWidth: 2
#printWidth: 120
#endOfLine: lf

#==========================================================#
# options (default)

semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
requirePragma: false
insertPragma: false
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
embeddedLanguageFormatting: auto
singleAttributePerLine: false
