# prettier ships with a handful of format options
# that can be changed in this configuration file
#
# https://prettier.io/docs/en/options.html
# https://prettier.io/docs/en/configuration.html
#
# set in .editorconfig
# useTabs: false
# tabWidth: 2
# printWidth: 120
# endOfLine: lf
#
# default
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
requirePragma: false
insertPragma: false
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
embeddedLanguageFormatting: auto
singleAttributePerLine: false
