# format options
#
# https://prettier.io/docs/en/options.html

# printWidth: 120 (set in .editorconfig)
# tabWidth: 2 (set in .editorconfig)
# useTabs: false (set in .editorconfig)
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
requirePragma: false
insertPragma: false
proseWrap: preserve
htmlWhitespaceSensitivity: css
vueIndentScriptAndStyle: false
# endOfLine: lf (set in .editorconfig)
embeddedLanguageFormatting: auto
singleAttributePerLine: false
